### ISSUE TITLE
Código de verificación

### ISSUE THREAD

**Issue by walterortizz** [ale-strada/api-m9-vercel#1]
Hola Ale, cómo estás?. Te cuento en el primer endpoint, al ingresar mi correo eléctronico no me estaría llegando el email, intenté con varios correos y nada, luego probé con desafíos de otras personas y el correo me llega correctamente, avisame si se trata de un error mío o quizá esté algo mal en la api, de cualquier modo lo dejo como "necesita ajustes" y ni bien lo vuelvas a enviar le doy otra ojeada.

**Comment by ale-strada** [comment]
Hola @walterARG2K. como va? Muchas gracias por tomarte tantas molestias para probar la Api. Ya lo estuve viendo, me faltaba un await frente a la invocacion de la funcion sendEmail. Lo confuso era que en local funcionaba perfecto. Solo fallo en produccion y no me habia dado cuenta. Ya volvi a subir el desafio. Gracias de nuevo! Saludos!

**Comment by walterortizz** [comment]
Perfecto entonces, cuándo me vuelva a aparecer tu desafío para revisar lo voy a volver a mirar.
